"""
L0 driver — regenerates the asserted stress corpus from the seed data and the oracle.

  scripts/corpus/build.py            write the artefacts
  scripts/corpus/build.py --check    verify the committed artefacts are up to date

The generated files are committed. That is deliberate: they are the portable artefact
other engines consume, and a reviewer must be able to read the expectation in the diff.
--check keeps them honest by regenerating into memory and comparing.

Nothing is written unless every stage passes: the model resolves, the seed satisfies its
schema and all twelve adversarial properties, and the oracle evaluates every service
without refusing. A refusal is not routed around — it means the corpus contains a case
whose answer we cannot predict, and shipping it would mean asserting whatever the engine
happened to produce.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import battery
import emit
import flat
import model
import oracle
import query
import seed
from model import STRESS

DATA_FILE = STRESS / "93-testdata.pure"
SERVICES_FILE = STRESS / "92-services.pure"
FANOUT_FILE = STRESS / "94-fanout-services.pure"

HEADER = """// GENERATED by scripts/corpus/build.py -- do not edit by hand.
//
// Seed data for the stress corpus: {rows} rows across {tables} tables, carrying the
// adversarial properties A1..A12 documented in scripts/corpus/seed.py (orphan and NULL
// foreign keys, zero-child entities, ties, skew, empty-vs-NULL strings, apostrophes and
// a broken two-hop chain). Regenerate with `python3 scripts/corpus/build.py`.
"""

FANOUT_HEADER = """// The fan-out battery. Every ->count() here crosses a to-many association, which the
// original 12 services never did (0 of 530 projection paths). Expectations come from the
// reference evaluator; the zeroes are the point -- see scripts/corpus/battery.py.
//
// GENERATED by scripts/corpus/build.py -- do not edit by hand.
"""

SERVICES_HEADER = """// Stress test queries as portable Service definitions, each carrying a testSuite whose
// expectation was computed by the reference evaluator in scripts/corpus/oracle.py from
// the seed data in 93-testdata.pure -- NOT captured from engine output.
//
// GENERATED by scripts/corpus/build.py -- do not edit by hand. Edit the seed or the
// queries and regenerate, so the expectation can never drift from the data.
"""


def split_services(text: str) -> tuple[str, list[tuple[str, str]]]:
    """(preamble, [(name, body)]) where body runs from `Service x` to its closing brace."""
    marker = "\n###Service\n"
    i = text.index(marker)
    preamble, rest = text[:i], text[i + len(marker):]
    out, cur, buf, depth, started = [], None, [], 0, False
    for line in rest.splitlines():
        if line.startswith("Service ") and cur is None:
            cur, buf, depth, started = line.split()[1], [line], 0, False
        if cur is None:
            continue
        if line is not buf[0]:
            buf.append(line)
        depth += line.count("{") - line.count("}")
        if "{" in line:
            started = True
        if started and depth == 0:
            out.append((cur, "\n".join(buf)))
            cur = None
    if cur is not None:
        raise ValueError(f"unterminated service {cur}")
    return preamble, out


def generate() -> dict[Path, str]:
    c = model.load()
    TABLES = flat.all_tables(c)

    problems = model.check(c)
    if problems:
        raise SystemExit("model does not resolve:\n  " + "\n  ".join(problems[:10]))
    problems = seed.check(c) + flat.check(c, TABLES['TRADE_FLAT'])
    if problems:
        raise SystemExit("seed is invalid:\n  " + "\n  ".join(problems[:10]))

    specs = query.load()

    out = []
    for spec in specs:
        rows = oracle.evaluate(c, spec, TABLES)      # raises Fanout, never guesses
        expected = oracle.as_json_rows(c, spec, rows)
        nulls = sum(1 for r in expected for v in r.values() if v is None)
        note = (f"{len(expected)} rows x {len(spec.projections)} columns, "
                f"{nulls} NULL cells from orphan/absent foreign keys")
        out.append(emit.service(spec, expected, note))

    services = SERVICES_HEADER + "\n###Service\n" + "\n\n".join(out) + "\n"

    # L2: the two sides of the invariance pair must agree before anything is emitted.
    # If they do not, the fixture is wrong — the denormalization does not carry the same
    # facts — and shipping both would produce two tests that disagree for a reason that
    # has nothing to do with the engine.
    key = lambda rs: sorted(json.dumps(r, sort_keys=True) for r in rs)
    inv = [(s.short, key(oracle.as_json_rows(c, s, oracle.evaluate(c, s, TABLES))))
           for s in battery.INVARIANCE]
    base_name, base = inv[0]
    for name, rows in inv[1:]:
        if rows != base:
            only_a = [r for r in base if r not in rows][:2]
            only_b = [r for r in rows if r not in base][:2]
            raise SystemExit(
                f"mapping invariance FAILS in the fixture itself "
                f"({base_name} vs {name}):\n"
                f"  {base_name}-only: {only_a}\n  {name}-only: {only_b}")

    fan = []
    for spec in battery.SPECS:
        rows = oracle.evaluate(c, spec, TABLES)
        expected = oracle.as_json_rows(c, spec, rows)
        zeros = sum(1 for r in expected for k, v in r.items()
                    if any(p.agg for p in spec.projections if p.alias == k) and v == 0)
        note = (f"{len(expected)} rows; {zeros} of the aggregate cells are ZERO -- an "
                f"entity with no children. COUNT(*) over the outer join would return 1.")
        fan.append(emit.service(spec, expected, note))
    fanout = FANOUT_HEADER + "\n###Service\n" + "\n\n".join(fan) + "\n"
    data = (HEADER.format(rows=sum(len(v) for v in TABLES.values()),
                          tables=len(TABLES))
            + "\n" + emit.data_element(c, TABLES) + "\n")
    return {DATA_FILE: data, SERVICES_FILE: services, FANOUT_FILE: fanout}


def main() -> None:
    check = "--check" in sys.argv
    files = generate()
    stale = []
    for path, text in files.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if not check:
            path.write_text(text)
    for path, text in files.items():
        print(f"  {path.relative_to(STRESS.parents[4]) if False else path.name:<22} "
              f"{len(text.splitlines()):>5} lines"
              + ("  STALE" if path in stale else "  up to date"))
    if check and stale:
        raise SystemExit(
            f"\n{len(stale)} generated file(s) are stale; run scripts/corpus/build.py")
    if not check:
        print("\nwrote" if stale else "\nno changes")


if __name__ == "__main__":
    main()
