"""
Emits the artefacts for cross-engine differential testing.

The same corpus, the same seed, two independent implementations. legend-engine executes
the .pure testSuites directly; legend-lite generates SQL that has to be run against a
database holding the identical rows. This writes what the legend-lite side needs:

  target/diff/seed.sql              DDL + INSERTs for DuckDB, from the DECLARED schema
  target/diff/expected/<Svc>.txt    the oracle's answer in a normalised form

Both sides are compared in a normalised text form rather than as JSON, so that neither
side's JSON library, float formatter or key ordering can influence the verdict. The first
line of each expectation names the column kinds; the reader uses them to normalise, which
is what keeps `190500.0` on one side and `190500` on the other from being a false
difference.

This is the third assertion mechanism from the plan. Unlike the oracle it cannot be wrong
about semantics — it only reports that two engines disagree — and unlike a metamorphic
relation it cannot be satisfied vacuously. Its blind spot is equally plain: a defect both
engines share is invisible to it.
"""
from __future__ import annotations

from pathlib import Path

import battery
import model
from quarantine import LITE_QUARANTINE
import oracle
import query
import seed
from model import STRESS

OUT = STRESS.parents[4] / "core" / "target" / "diff"

# Declared type -> DuckDB type. BIT is Legend's boolean; DuckDB spells it BOOLEAN.
_DUCK = {"string": "VARCHAR", "int": "INTEGER", "float": "DOUBLE",
         "bool": "BOOLEAN", "date": "DATE", "timestamp": "TIMESTAMP"}

NULL = "~"


def _sql_literal(v, kind: str) -> str:
    if v is None:
        return "NULL"
    if kind == "bool":
        return "TRUE" if v else "FALSE"
    if kind in ("int", "float"):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def seed_sql(c: model.Corpus) -> str:
    out = ["-- GENERATED by scripts/corpus/differential.py -- do not edit.",
           "-- DDL comes from the DECLARED store schema, not from CSV type inference, so a",
           "-- column that happens to be all-NULL in the seed still gets its real type."]
    for name, rows in seed.TABLES.items():
        cols = c.tables[name].columns
        decls = ", ".join(f"{n} {_DUCK[col.kind]}" for n, col in cols.items())
        out.append(f"\nDROP TABLE IF EXISTS {name};")
        out.append(f"CREATE TABLE {name} ({decls});")
        for r in rows:
            vals = ", ".join(_sql_literal(r.get(n), col.kind) for n, col in cols.items())
            out.append(f"INSERT INTO {name} VALUES ({vals});")
    return "\n".join(out) + "\n"


def normalise(v, kind: str) -> str:
    if v is None:
        return NULL
    if kind == "float":
        return f"{float(v):.6f}"
    if kind == "bool":
        return "true" if v else "false"
    return str(v)


def expected_text(c: model.Corpus, spec) -> str:
    rows = oracle.evaluate(c, spec, seed.TABLES)
    kinds = oracle.kinds(c, spec)
    aliases = [p.alias for p in spec.projections]
    head = "|".join(f"{a}:{kinds[a]}" for a in aliases)
    # Sorted, because EqualToJson compares unordered and the SQL carries no ORDER BY
    # unless the query asked for one; row order is not part of the claim.
    body = sorted("|".join(normalise(r[a], kinds[a]) for a in aliases) for r in rows)
    return "\n".join([head, *body]) + "\n"


def main() -> None:
    c = model.load()
    (OUT / "expected").mkdir(parents=True, exist_ok=True)
    (OUT / "seed.sql").write_text(seed_sql(c))

    specs = query.load() + battery.SPECS
    for spec in specs:
        # The expectation is written WITHOUT the timestamp reformatting the JSON path
        # applies -- that is a legend-engine serialisation detail, not a value difference,
        # and the SQL side never sees it.
        (OUT / "expected" / f"{spec.short}.txt").write_text(expected_text(c, spec))
    # legend-lite's OWN known divergences from the reference — not legend-engine's. The
    # two lists are different by construction: the F6 fan-out services fail in
    # legend-engine and agree here.
    (OUT / "expected" / "QUARANTINE.txt").write_text(
        "".join(f"{n.split('::')[-1]}\t{q[0]}\t{q[1]}\n"
                for n, q in sorted(LITE_QUARANTINE.items())))

    print(f"seed.sql: {len(seed_sql(c).splitlines())} lines, "
          f"{sum(len(v) for v in seed.TABLES.values())} rows")
    print(f"expectations: {len(specs)} services -> {OUT / 'expected'}")


if __name__ == "__main__":
    main()
