"""
Emits the artefacts for cross-engine differential testing.

The same corpus, the same seed, two independent implementations. legend-engine executes
the .pure testSuites directly; legend-lite generates SQL that has to be run against a
database holding the identical rows. This writes what the legend-lite side needs:

  target/diff/seed.sql              DDL + INSERTs for DuckDB, from the DECLARED schema
  target/diff/expected/<Svc>.txt    the oracle's answer in a normalised form

Both sides are compared in a normalised text form rather than as JSON, so that neither
side's JSON library, float formatter or key ordering can influence the verdict. The first
line of each expectation names the column kinds; the reader uses them to normalise, which
is what keeps `190500.0` on one side and `190500` on the other from being a false
difference.

This is the third assertion mechanism from the plan. Unlike the oracle it cannot be wrong
about semantics — it only reports that two engines disagree — and unlike a metamorphic
relation it cannot be satisfied vacuously. Its blind spot is equally plain: a defect both
engines share is invisible to it.
"""
from __future__ import annotations

from pathlib import Path

import battery
import flat
import model
import stacks
from quarantine import LITE_QUARANTINE
import oracle
import query
import seed
from model import STRESS

OUT = STRESS.parents[4] / "core" / "target" / "diff"

# Declared type -> DuckDB type. BIT is Legend's boolean; DuckDB spells it BOOLEAN.
_DUCK = {"string": "VARCHAR", "int": "INTEGER", "float": "DOUBLE",
         "bool": "BOOLEAN", "date": "DATE", "timestamp": "TIMESTAMP"}

NULL = "~"


def _sql_literal(v, kind: str) -> str:
    if v is None:
        return "NULL"
    if kind == "bool":
        return "TRUE" if v else "FALSE"
    if kind in ("int", "float"):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def seed_sql(c: model.Corpus, TABLES) -> str:
    # Views are excluded: the engine inlines their GROUP BY, so creating a real table of
    # the same name would shadow the view and stop testing the aggregation.
    out = ["-- GENERATED by scripts/corpus/differential.py -- do not edit.",
           "-- DDL comes from the DECLARED store schema, not from CSV type inference, so a",
           "-- column that happens to be all-NULL in the seed still gets its real type."]
    for name, rows in TABLES.items():
        if name in c.views:
            continue
        cols = c.tables[name].columns
        decls = ", ".join(f"{n} {_DUCK[col.kind]}" for n, col in cols.items())
        out.append(f"\nDROP TABLE IF EXISTS {name};")
        out.append(f"CREATE TABLE {name} ({decls});")
        for r in rows:
            vals = ", ".join(_sql_literal(r.get(n), col.kind) for n, col in cols.items())
            out.append(f"INSERT INTO {name} VALUES ({vals});")
    return "\n".join(out) + "\n"


def normalise(v, kind: str) -> str:
    if v is None:
        return NULL
    if kind == "float":
        return f"{float(v):.6f}"
    if kind == "bool":
        return "true" if v else "false"
    return str(v)


def expected_text(c: model.Corpus, spec, TABLES) -> str:
    rows = oracle.evaluate(c, spec, TABLES)
    kinds = oracle.kinds(c, spec)
    # After a groupBy only the keys and aggregates survive; the other projected columns
    # are gone, so the header must follow the RESULT shape, not the projection list.
    aliases = ([*spec.group_by, *(name for name, _, _ in spec.aggs)]
               if spec.group_by else [p.alias for p in spec.projections])
    head = "|".join(f"{a}:{kinds[a]}" for a in aliases)
    # Sorted, because EqualToJson compares unordered and the SQL carries no ORDER BY
    # unless the query asked for one; row order is not part of the claim.
    body = sorted("|".join(normalise(r[a], kinds[a]) for a in aliases) for r in rows)
    return "\n".join([head, *body]) + "\n"


def main() -> None:
    c = model.load()
    TABLES = flat.all_tables(c)
    # Clear first. A service that stops being emitted — because it moved out of scope, or
    # was renamed — otherwise leaves its old expectation behind, and the Java side keeps
    # comparing against a file nothing generates any more.
    exp_dir = OUT / "expected"
    if exp_dir.is_dir():
        for stale in exp_dir.glob("*.txt"):
            stale.unlink()
    exp_dir.mkdir(parents=True, exist_ok=True)
    (OUT / "seed.sql").write_text(seed_sql(c, TABLES))

    # Graph-fetch services are OUT OF SCOPE for the differential.
    #
    # The comparison here is a normalised FLAT row — `col|col|...` with a header of column
    # kinds — which cannot represent a tree. Emitting an expectation for a graph spec
    # produced an empty body and every actual row reported as a disagreement: noise that
    # looks exactly like a real finding.
    #
    # Covering them would mean either teaching this harness tree comparison or having
    # legend-lite produce the same serialization. Neither is done, so they are skipped
    # HERE and remain fully asserted against legend-engine by run.py.
    # Also out of scope: any spec whose expectation is MIRRORED. Those roots have no
    # table — an M2M target is not read from a store — so there is nothing for the oracle
    # to evaluate and nothing for legend-lite to generate SQL against.
    generated = stacks.build(c, {k for k, v in TABLES.items() if v})
    # Services legend-lite cannot even load the model for (Measure) are out of scope on
    # this side; run.py still asserts them against legend-engine.
    lite_blind = {"MU0_MonetaryTrade"}
    specs = [s for s in query.load() + list(battery.SPECS) + generated
             if s.graph is None and getattr(s, "mirrors", None) is None
             and s.short not in lite_blind]
    for spec in specs:
        # The expectation is written WITHOUT the timestamp reformatting the JSON path
        # applies -- that is a legend-engine serialisation detail, not a value difference,
        # and the SQL side never sees it.
        (OUT / "expected" / f"{spec.short}.txt").write_text(expected_text(c, spec, TABLES))
    # legend-lite's OWN known divergences from the reference — not legend-engine's. The
    # two lists are different by construction: the F6 fan-out services fail in
    # legend-engine and agree here.
    (OUT / "expected" / "QUARANTINE.txt").write_text(
        "".join(f"{n.split('::')[-1]}\t{q[0]}\t{q[1]}\n"
                for n, q in sorted(LITE_QUARANTINE.items())))

    print(f"seed.sql: {len(seed_sql(c, TABLES).splitlines())} lines, "
          f"{sum(len(v) for v in TABLES.values())} rows")
    skipped = sum(1 for s in battery.SPECS
                  if s.graph is not None or getattr(s, "mirrors", None) is not None)
    print(f"expectations: {len(specs)} services -> {OUT / 'expected'}"
          + (f"  ({skipped} graph-fetch services skipped: flat comparison cannot "
             f"represent a tree; M2M targets have no table)" if skipped else ""))


if __name__ == "__main__":
    main()
