"""
Function tests — a SECOND testable harness, structurally unlike the Service one.

Everything else in this corpus is a Service testSuite. A function carries its tests as an
unnamed brace block immediately after its body, supplies parameters positionally inside
the test line rather than in a `parameters:` block, and is addressed by a MANGLED testable
id that encodes its signature:

    stress::rules::tradesByStatus_String_1__TabularDataSet_1_

Two constraints the Service harness does not have:
  * the function must embed its runtime with `->from(mapping, runtime)` — the runner reads
    the runtime out of the function definition, and more than one is an error;
  * the test name must be the function's SIMPLE name, without its package.

Worth having for its own sake: a second harness is a second code path over the same
model, and this corpus already has three findings that only appear when the path changes.
"""
from __future__ import annotations

import json

import emit
import model
import oracle
from query import Pred, Proj, Spec

MAPPING = "stress::AllMapping"
RUNTIME = "stress::RT"
STORE = "store::DB"
DATA = "stress::TestData"

# Pure type -> the signature fragment used in the mangled testable id.
_MANGLE = {"String": "String_1_", "Float": "Float_1_", "Integer": "Integer_1_"}


def _spec(name: str, param_value, columns: list[tuple[str, str]]) -> Spec:
    s = Spec(f"stress::rules::{name}", "", "", "trading::Trade")
    s.projections = [Proj(a, p.split(".")) for a, p in columns]
    s.filters = [Pred(["status"], "==", param_value)]
    s.paradigm = "tds"
    return s


COLUMNS = [("tradeId", "tradeId"), ("notional", "notional"), ("side", "side"),
           ("instrName", "instrument.name")]

# (function name, parameter type, [(test id, argument)])
FUNCTIONS = [
    ("tradesByStatus", "String",
     [("executed", "EXECUTED"),
      # 'SETTLED' matches exactly one trade, and 'EXECUTE' -- one letter short of
      # EXECUTED -- matches exactly one too. A filter that was doing prefix matching
      # rather than equality would pass the first and fail these.
      ("settled", "SETTLED"),
      ("nearMiss", "EXECUTE"),
      # No trade has this status, so the function must return an EMPTY tds, not null and
      # not an error.
      ("noneAtAll", "NOSUCHSTATUS")]),
]


def testable_id(name: str, param_type: str) -> str:
    return f"stress::rules::{name}_{_MANGLE[param_type]}_TabularDataSet_1_"


def render(c: model.Corpus, tables: dict[str, list[dict]]) -> str:
    out = ["""// GENERATED by scripts/corpus/build.py -- do not edit by hand.
//
// The FUNCTION test harness: a function carries its tests in a brace block after its
// body, seeds the store by name, and passes parameters positionally. Expectations come
// from the same reference evaluator as every Service test.
###Pure"""]
    for name, ptype, cases in FUNCTIONS:
        lams = ",\n      ".join(f"t|{('$t.' + '.'.join(p.path))}" for p in
                                _spec(name, "", COLUMNS).projections)
        names = ", ".join(f"'{a}'" for a, _ in COLUMNS)
        out.append(f"""
function {name and f'stress::rules::{name}'}(status: {ptype}[1]): meta::pure::tds::TabularDataSet[1]
{{
  trading::Trade.all()
    ->filter(t|$t.status == $status)
    ->project(
      [
      {lams}
      ],
      [{names}]
    )
    ->from({MAPPING}, {RUNTIME})
}}
{{
  testSuite_1
  (
    {STORE}: {DATA};""")
        for test_id, arg in cases:
            spec = _spec(name, arg, COLUMNS)
            rows = oracle.as_json_rows(c, spec, oracle.evaluate(c, spec, tables))
            payload = emit._pure_str(json.dumps(rows, separators=(",", ":")))
            out.append(f"    {test_id} | {name}('{arg}') => (JSON) '{payload}';")
        out.append("  )\n}")
    return "\n".join(out) + "\n"


def testables() -> list[str]:
    return [testable_id(n, p) for n, p, _ in FUNCTIONS]
