"""
Makes the hier:: feature mappings EXECUTE, rather than merely compile.

61-inheritance.pure and 62-mapping-features.pure brought the mapping/store taxonomy to
35 of 35 -- but a construct that only compiles proves the front end accepts it, not that the
engine computes anything correct with it. The dynafunction mappings in particular were
worth nothing until something checked what `concat` over a NULL actually returns.

So this emits the runtime, the seeded data and the services for the hier:: classes whose
every property the ORACLE can resolve independently:

    hier::Instrument    5 plain columns -- the inheritance hierarchy's root set
    hier::IssuerLabel   1 column + THREE dynafunctions (concat, toUpper, toLower)

Deliberately NOT hier::Issuer or hier::InstrumentReach. Their `profile` (a Binding
transformer) and `countryName` (a two-hop join chain) are in `c.unparsed` -- the reader has
no rule for either, so the oracle cannot compute an expectation, and a service over them
would have to take its expected values from the engine under test. That is the one thing
this corpus refuses to do, so those two stay compile-only until the reader models them.

The dynafunction service is the point of the exercise. Every expanded table carries a NULL
by construction (property A2), so `concat(LEGAL_NAME, CONTACT_EMAIL)` will meet one -- and
the oracle asserts NULL, not the other argument and not the empty string, from an
implementation written against what concat MEANS rather than against what the engine
returned.
"""
from __future__ import annotations

import model
from query import Proj, Spec

# Each hier:: store has its own runtime, and each runtime its own connection ID. Two
# identifiedConnections sharing an id inside one runtime is rejected outright:
# "Runtime connection with ID 'environment' has already been specified".
# store -> (mapping, runtime, connection id, data element). One data element per STORE:
# a runtime connects one store, and an element carrying another store's tables fails at
# session setup with an error that names the table rather than the packaging.
BINDINGS = {
    "hier::IssuerDB": ("hier::IssuerMapping", "hier::IssuerRT", "issuerEnv",
                       "hier::IssuerData"),
    "hier::HierDB": ("hier::HierMapping", "hier::HierRT", "hierEnv",
                     "hier::InstrumentData"),
}
CONN = "hier::HierConn"

# Classes whose every property the oracle can resolve. Anything with an entry in
# c.unparsed is excluded by construction rather than by a hand-written list, so a reader
# that learns to model join chains automatically widens this.
def executable(c: model.Corpus) -> list[str]:
    blocked = {cls for cls, _prop in c.unparsed}
    return [cls for cls in sorted(c.main_table)
            if cls.startswith("hier::") and cls not in blocked
            and len(c.columns.get(cls, {})) >= 2]


def runtime_text() -> str:
    runtimes = "\n\n".join(
        f"Runtime {rt}\n{{\n    mappings:\n    [\n        {mp}\n    ];\n"
        f"    connections:\n    [\n        {db}: [ {cid}: {CONN} ]\n    ];\n}}"
        for db, (mp, rt, cid, _dt) in sorted(BINDINGS.items()))
    return f"""// GENERATED by scripts/corpus/hier.py -- do not edit by hand.
//
// Connection, runtimes and seeded data for the hier:: feature domain. Its tables live in
// stores separate from store::DB, and test data is bound to a CONNECTION, so they need
// their own -- and each runtime needs its own connection ID, because two
// identifiedConnections sharing one inside a runtime is rejected outright.
###Connection
RelationalDatabaseConnection {CONN}
{{
    type: DuckDB;
    specification: DuckDB {{ }};
    auth: Test;
}}


###Runtime
{runtimes}
"""


def specs(c: model.Corpus) -> list[Spec]:
    """One service per oracle-resolvable hier:: class."""
    out = []
    for n, cls in enumerate(executable(c)):
        cols = c.columns.get(cls, {})
        table = c.tables.get(c.main_table.get(cls, ""))
        if table is None or not table.pk:
            continue
        ident = next((p for p, col in cols.items() if col == table.pk[0]), None)
        if ident is None:
            continue

        dyn = [p for p in sorted(cols) if (cls, p) in c.dyna]
        plain = [p for p in sorted(cols) if p != ident and p not in dyn]
        short = cls.split("::")[-1]

        note = (f"{len(dyn)} of the projected columns are DYNAFUNCTIONS "
                f"({', '.join(c.dyna[(cls, p)][0] for p in dyn)}); the oracle evaluates "
                f"each independently of the engine." if dyn else
                "Plain columns over the inheritance hierarchy's root set.")

        spec = Spec(f"stress::H{n}_{short}", f"/stress/h{n}",
                    f"Executes the hier:: feature mapping for {cls}. {note} "
                    f"Generated by scripts/corpus/hier.py -- the class list is derived from "
                    f"what the ORACLE can resolve, so a property the reader cannot model "
                    f"(a join chain, a Binding transformer) excludes its class automatically "
                    f"rather than being remembered in a list here.", cls)
        spec.projections = ([Proj(ident, [ident])]
                            + [Proj(p, [p]) for p in plain + dyn])
        spec.sort = (ident, False)
        db = getattr(table, "database", "")
        if db not in BINDINGS:
            continue
        mapping, runtime, conn, data = BINDINGS[db]
        spec.mapping = mapping
        spec.runtime = runtime
        spec.connection = conn
        spec.data_element = data
        out.append(spec)
    return out


if __name__ == "__main__":
    import flat

    c = model.load()
    tables = flat.all_tables(c)
    print("oracle-resolvable hier:: classes:", executable(c))
    print("blocked (reader cannot model a property):",
          sorted({cls for cls, _ in c.unparsed}))
    for s in specs(c):
        d = sum(1 for p in s.projections if (s.root, p.alias) in c.dyna)
        print(f"  {s.name.split('::')[-1]:<24}{len(s.projections)} cols, {d} dynafunction(s)")
