package com.legend.tools.generators;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * A generated file AS THIS CHECKOUT HOLDS IT: the generator's output with the
 * line endings of its committed copy. {@code write_generated_files} (defs.bzl)
 * runs this between every generator and the diff test that compares its output
 * with the committed copy byte for byte.
 *
 * <pre>
 *   CheckoutLineEndings &lt;committed copy&gt; &lt;generated&gt; &lt;output&gt;
 * </pre>
 *
 * <p>A generator writes {@code '\n'} on every machine (ClaimsGenerator says why).
 * A checkout's line endings are git's choice. CI checks out LF on every platform
 * (gates-run.yml sets {@code core.autocrlf false}), but Git for Windows installs
 * with {@code core.autocrlf=true}. That setting checks out a file whose committed
 * bytes hold no CR with CRLF on every line, and checks out a file that holds a
 * CR exactly as committed. This applies the same rule from the checkout's side:
 * LF becomes CRLF when every line of the committed copy ends CRLF and the
 * generated bytes hold no CR. Otherwise the generated bytes pass through
 * unchanged, and the diff test judges them as they are.
 */
public final class CheckoutLineEndings {

    private CheckoutLineEndings() {}

    public static void main(String[] args) throws IOException {
        if (args.length != 3) {
            throw new IllegalArgumentException("usage: CheckoutLineEndings <committed copy> <generated> <output>");
        }
        byte[] committed = Files.readAllBytes(Path.of(args[0]));
        byte[] generated = Files.readAllBytes(Path.of(args[1]));
        Files.write(Path.of(args[2]), checkedOut(committed, generated));
    }

    /** {@code generated} as git checks it out where the file's copy is {@code committed}. */
    static byte[] checkedOut(byte[] committed, byte[] generated) {
        if (!everyLineEndsCrlf(committed) || holdsCr(generated)) {
            return generated;
        }
        ByteArrayOutputStream out = new ByteArrayOutputStream(generated.length + generated.length / 32);
        for (byte b : generated) {
            if (b == '\n') {
                out.write('\r');
            }
            out.write(b);
        }
        return out.toByteArray();
    }

    /** At least one line break, and a CR before every LF. */
    static boolean everyLineEndsCrlf(byte[] text) {
        boolean any = false;
        for (int i = 0; i < text.length; i++) {
            if (text[i] == '\n') {
                if (i == 0 || text[i - 1] != '\r') {
                    return false;
                }
                any = true;
            }
        }
        return any;
    }

    private static boolean holdsCr(byte[] text) {
        for (byte b : text) {
            if (b == '\r') {
                return true;
            }
        }
        return false;
    }
}
